[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Environment variables for production
[context.production.environment]
  VITE_SUPABASE_URL = "https://lmqagaenmseopcctkrwv.supabase.co"

# Proxy redirect for Supabase functions
[[redirects]]
  from = "/functions/v1/*"
  to = "https://lmqagaenmseopcctkrwv.supabase.co/functions/v1/:splat"
  status = 200
  force = true # Ensure this rule is applied

# SPA routing configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "http://hypsights.com/*"
  to = "https://hypsights.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.hypsights.com/*"
  to = "https://hypsights.com/:splat"
  status = 301
  force = true